services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/steps.db:/app/data/steps.db
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.local
    volumes:
    - ./client:/app
    - /app/node_modules
    # command: ["npm", "run", "dev"]
    depends_on:
      - server

volumes:
  steps_db:
